services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: 
        ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 3

  chess_app:
    build: .
    container_name: chess_app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5556:5556"
    command: ["sh", "-c", "python3 -m online.network_server"]
    restart: always  # Set the restart policy
    healthcheck:
      test: ["CMD", "python3", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: