name: Build and Test with SonarQube Analysis

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  # Job to set up dependencies and cache Python packages
  setup:
    name: Set up Python and Cache Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache Python packages
      - name: Cache dependencies
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  # Linting job
  lint:
    name: Lint Code with Ruff
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Restore cached dependencies
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      # Install Ruff
      - name: Install Ruff
        run: pip install ruff

      # Lint the code
      - name: Lint with Ruff
        run: ruff check .
        continue-on-error: true

  # Testing job
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: userauth
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Install test dependencies
        run: |
          pip install tox pytest pytest-cov tornado pycryptodome PyQt5 chess psycopg2-binary
          sudo apt-get install -y 

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          tox -e py

      # Upload coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  # SonarQube analysis job
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [setup, lint, test]

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Download coverage report from test job
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      # Restore cached dependencies
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # Set up Python (Specify a version since matrix is not used here)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Run SonarQube analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optional: Fail job if Quality Gate fails
      # - name: SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
